ALTER TABLE hire
  ADD COLUMN payment_proof VARCHAR(255) DEFAULT NULL,
  ADD COLUMN payment_date DATETIME DEFAULT NULL,
  ADD COLUMN payer_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN reference_number VARCHAR(255) DEFAULT NULL; 